### PR TITLE
add missing notification type NodeReset

### PR DESCRIPTION
**Pull request by nechry**
see https://github.com/OpenZWave/open-zwave/blob/cfdcceae0368146eab72fc2ae82910b777bedc2a/cpp/src/Driver.cpp#L2842

### CODE REVIEW

**Comment by bibi21000** [comment]
Did you test it ? 
I think this patch will cause a lot of troubles.
You insert the new notification inside the list, sure of that ?
https://github.com/OpenZWave/python-openzwave/pull/56/commits/9a10a241ad56e9925567aa9dbeb149773809c050#diff-8eb94754329340f63f6b2defcbdfd473R167
I feel very disappointed if the openvawe team did updates like this ;)
For notifications, look at https://github.com/OpenZWave/open-zwave/blob/5c7ac3329a4b18c644bd34a70454c102a3fdb0ef/cpp/src/Notification.h#L97

About the sigma naming, python-openzwave is only a wrapper to the openzwave librabry, so we must be close to their naming.
Propose your update to the lib and we'll update python-openzwave in consequence.
By the way, 0x34: 'COMMAND_CLASS_ZIP_ADV_CLIENT' is no longer available in openzwave so we can update it.

**Comment by nechry** [comment]
I find my mistake:
https://github.com/OpenZWave/open-zwave/blob/5c7ac3329a4b18c644bd34a70454c102a3fdb0ef/dotnet/src/ZWNotification.h#L68
so yes the notification mist be add at the end of the list like you point:
https://github.com/OpenZWave/open-zwave/blob/5c7ac3329a4b18c644bd34a70454c102a3fdb0ef/cpp/src/Notification.h#L97
I will change. and update the PR

**Comment by nechry** [comment]
Theres CC are also not present in sigma documentation:
http://zwavepublic.com/sites/default/files/SDS12657-12%20-%20Z-Wave%20Command%20Class%20Specification%20A-M.pdf

COMMAND_CLASS_ZIP_SERVER                = 36  # 0x24
COMMAND_CLASS_CHIMNEY_FAN               = 42  # 0x2A
COMMAND_CLASS_ZIP_CLIENT                = 46  # 0x2E
COMMAND_CLASS_ZIP_ADV_SERVICES          = 47  # 0x2F
COMMAND_CLASS_THERMOSTAT_HEATING        = 56  # 0x38
COMMAND_CLASS_COMPOSITE                 = 141  # 0x8D
COMMAND_CLASS_AV_CONTENT_DIRECTORY_MD   = 149  # 0x95
COMMAND_CLASS_AV_RENDERER_STATUS        = 150  # 0x96
COMMAND_CLASS_AV_CONTENT_SEARCH_MD      = 151  # 0x97
COMMAND_CLASS_AV_TAGGING_MD             = 153  # 0x99

step by step we will clean it.

I will propose the renaming in ozw.

**Comment by nechry** [comment]
Hello, I will rename in openzwave librarie the existing CCs to match name from Sigma SDK in November.
more details about this changes in openzwave google groups https://groups.google.com/forum/#!topic/openzwave/xTXsiApyJ6Y

when this change will be attach to master branch I will propose a new PR for rename in Wrapper.

**Comment by bibi21000** [comment]
Applied manually thanks

**Pull request closed without merging**
