### PR TITLE
Updated cython wrappers of ValueID enums for Cython 0.23 (Fixes #10)

### LINKED ISSUE #10: Python3 branch is not compiling
I get these errors when compiling: 

```
src-lib/libopenzwave/libopenzwave.cpp:922:87: error: ‘ValueType’ is not an enumerator-name
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueType(enum OpenZWave::ValueType value);
                                                                                       ^
src-lib/libopenzwave/libopenzwave.cpp:922:98: error: ‘ValueType’ in namespace ‘OpenZWave’ does not name a type
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueType(enum OpenZWave::ValueType value);
                                                                                                  ^
src-lib/libopenzwave/libopenzwave.cpp:934:88: error: ‘ValueGenre’ is not an enumerator-name
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueGenre(enum OpenZWave::ValueGenre value);
                                                                                        ^
src-lib/libopenzwave/libopenzwave.cpp:934:99: error: ‘ValueGenre’ in namespace ‘OpenZWave’ does not name a type
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueGenre(enum OpenZWave::ValueGenre value);
```

### PR DESCRIPTION
**Pull request by partofthething**
This update is required by changes made in Cython 0.23.

### CODE REVIEW

**Comment by partofthething** [comment]
This fixes #10

**Comment by bibi21000** [comment]
Thanks for your help.
I've merge your PR and fix it for Python 2. But it seems that there is some bugs left : https://hub.docker.com/r/bibi21000/python-openzwave/builds/ba9cv4wrtq7spt5bz6wgq2r/
Could you check that  accented characters are ok  with the following command : 
nosetests --verbosity=2 tests/api/test_node.py

**Comment by partofthething** [comment]
These tests pass on Python2 with your latest master. Looks like you fixed it already. 

```
$ nosetests --verbosity=2 tests/api/test_node.py
test_020_node_capabilities (tests.api.test_node.TestNode) ... ok
...
test_430_node_location (tests.api.test_node.TestNode) ... ok
test_431_node_location_accent (tests.api.test_node.TestNode) ... ok
...

----------------------------------------------------------------------
Ran 31 tests in 28.083s

OK
```

For python3, the accent one is skipped as Work in progress, but there is one failure that is a separate issue (longs aren't defined in 3). 

```
======================================================================
ERROR: test_340_node_baud_rate (tests.api.test_node.TestNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nick/codes/python-openzwave/tests/api/test_node.py", line 76, in test_340_node_baud_rate
    self.assertTrue(type(self.network.nodes[node_id].max_baud_rate) in [type(long()), type(int())])
NameError: name 'long' is not defined

----------------------------------------------------------------------
Ran 31 tests in 32.171s

FAILED (SKIP=4, errors=1)
```

**Comment by bibi21000** [comment]
It seems that your python3 branch is not sync : 
https://github.com/OpenZWave/python-openzwave/blob/python3/tests/api/test_node.py#L103
For long type, it should be fixed now

**Pull request closed without merging**
