### PR TITLE
Fix win64x deployment

### PR DESCRIPTION
**Pull request by dude0001**
Starting to resolve some of the issue identified in [132](https://github.com/OpenZWave/python-openzwave/issues/132). I am not ready for the PR to be accepted but wanted to start a conversation to make sure I'm on an acceptable path.

### CODE REVIEW

**Comment by dude0001** [comment]
Can someone take a look at what I have so far. There are a few things I still want to work on. However, I would like to know what else I should consider and how to further evaluate this works (e.g getting to work in pip or other acceptance criteria). 

The x64 build is making it further now, as far as the already failing x86 build [https://ci.appveyor.com/project/bibi21000/python-openzwave/build/0.5.0.122/job/3whnt8hc8mxpd914](https://ci.appveyor.com/project/bibi21000/python-openzwave/build/0.5.0.122/job/3whnt8hc8mxpd914). I see passing tests in pyozw_check for example.

Any thoughts on what to look at where the x64 and x86 builds are both failing now? This seems unrelated to what I'm attempting to fix reported in [132](https://github.com/OpenZWave/python-openzwave/issues/132). I think the building issue on Py 3.6 and VS 2017 x64 is resolved. I'm willing to help dig in to other issues if you can give me some feedback and background. 

Any thoughts on a nicer solutoin to this commit as well. This is prone to break if we stick in a fixed index. The goal would be to insert before or after existing elements of the same type. (https://github.com/OpenZWave/python-openzwave/pull/133/commits/b2553220420f1096810f513b54ba601015039157)[https://github.com/OpenZWave/python-openzwave/pull/133/commits/b2553220420f1096810f513b54ba601015039157]

**Comment by dude0001** [comment]
I am looking at the failing appveyor tests. I don't see how this is ever going to work.  

The appveyor script clones the openzwave repo to `C:\projects\python-openzwave\openzwave`
[https://github.com/OpenZWave/python-openzwave/blob/f6b99debaab873fde953b74bace9767304059cd4/appveyor.yml#L91](https://github.com/OpenZWave/python-openzwave/blob/f6b99debaab873fde953b74bace9767304059cd4/appveyor.yml#L91)

The appveyor error is looking for openzwave repo at `C:\projects\python-openzwave\openzwave-git\open-zwave-master`
https://ci.appveyor.com/project/bibi21000/python-openzwave/build/0.5.0.122/job/3whnt8hc8mxpd914

image

Is the correct context not getting selected for the appveyor build? It looks as simple as that, or changing the appveyor script to clone to openzwave repo to `C:\projects\python-openzwave\openzwave-git\open-zwave-master`.

**Comment by dude0001** [comment]
Okay, I got the VS 2017 appveyor builds to pass and getting the wheel files in the build artifacts. The VS 2015 build environment is hanging in python pyozw_win.py, not sure why yet.

I can troubleshoot the hanging VS 2015 build maybe this weekend. Any other feedback would be appreciated so I can help move this project forward for people in the Microsoft world.

@bibi21000 If you want to accept the PR before I look in to the VS 2015 issue, I am fine with that. I think this is already in a better state than it was and you'd have some wheel files for binary distribution. Welcome any review and feedback though.

Again, I am new to Python. So I am not sure how to test this with pip or help there. Willing to help if someone has any direction and feedback.

**Comment by dude0001** [comment]
I installed the [python_openzwave-0.4.9-cp36-cp36m-win_amd64.whl](https://ci.appveyor.com/api/buildjobs/swh6anhiokk45jm7/artifacts/dist%2Fpython_openzwave-0.4.9-cp36-cp36m-win_amd64.whl) file from the appveyor build and it is working. So, looks like this is on the right track. I'll maybe try to get the other VS versions builds working later today.

[pip and pyozw_check.log](https://github.com/OpenZWave/python-openzwave/files/2320713/pip.and.pyozw_check.log)

**Comment by kdschlosser** [comment]
setuptools.msvc does all of this for you. and it does it correctly and in a manner that all you have to do is apply the returned data to os.environ and set 2 other environment variables. I Have been through all of this already. I did a whole writeup in  #132

if you want a set of scripts that you can use for some ideas i can pass them over to ya. I gave up with it because it builds and runs fine on all python versions if you use VS2017 with SDK >= 8.1

**Comment by kdschlosser** [comment]
I can build a pyd file for all the different python versions and the pyd should be distributed instead of having it build on the users computer. there are simply way to many variables that can cause issues. I am not sure if there is a way to have pypy send the proper pyd file or if it is something that would have to be done in the setup script and downloaded.

**Comment by kdschlosser** [comment]
If you are interested. I have converted my original script and added it to a branch of python-openzwave on my repo. 

I have not tested it yet. It is to show how to locate msbuild.

This fully create a correct sln file as well as the vcproj file for visual studio 2010 2015 and 2017. I still have to run through some tests on that bit of it.

there are 2 files I have changed. pyozw_win and pyozw_setup

https://github.com/kdschlosser/python-openzwave/tree/solution_update

again this has not been tested at all. it is only to show a possible way to go about getting the proper environment in place

If you decide to opt for only using VS 2015 or 2017 then you MUST set 2 environment variables. DISTUTILS_USE_SDK=1 and MSSDK=windows sdk version otherwise you will get linker errors when building because the same compiler has to be used when building openzwave and libopenzwaves

disttutils compiles the libopenzwave extension. those 2 flags above are what tell distutils to use what is set in the environment and to not set up one of it's own.

**Pull request merged**
