### PR TITLE
AppVeyor CI should upload Windows wheels artifacts to pypi

### PR DESCRIPTION
**Pull request by dude0001**
I accidentally closed [PR #149](https://github.com/OpenZWave/python-openzwave/pull/149)

### CODE REVIEW

**Comment by dude0001** [comment]
@bibi21000 I think this looks right now, but still not seeing anything in PyPi. I am assuming you need to tag a release and do a build. Otherwise let, I am not sure how to see what has been sent up to PyPi and if it looks correct.

**Comment by bibi21000** [comment]
thanks for your help
I'll accept your PR in the next few days and look why upload don't work

**Comment by bibi21000** [comment]
Works fine after merging !!!!
Thank you

**Comment by dude0001** [comment]
I can confirm it installs on Windows from the .whl now no problem. No build tools needed. Thank you for merging!

**Pull request merged**
