### PR TITLE
Windows build of OpenZWave all python versions

### PR DESCRIPTION
**Pull request by kdschlosser**
This is a test to see if we get a correct build across all python versions x86 and x64.

If this works then you have something to use as a guide.

### CODE REVIEW

**Comment by kdschlosser** [comment]
rerun the appveyor build. it suceeded last time. there seems to be some kind of an issue with appveyor.

you can see the success here
https://ci.appveyor.com/project/bibi21000/python-openzwave/build/0.5.0.132

**Comment by kdschlosser** [comment]
OK I have managed to build on all visual c versions >= 10.0.  there are problems with 9.0 (python 2.7-3.3) that is not because of the compiler but because libopenzwave uses the map from the stdlib for C. and map does not have the method "at" in VC 9.0. unless there is an alternate to map that is common in all VC versions there is simply no way to compile using VC 9.0. But VC 10.0+ (VS 2010+) works just fine. and it can be used to compile for python 2.7-3.3 without any adverse affects.

**Comment by bibi21000** [comment]
thanks

**Comment by kdschlosser** [comment]
No worries m8 glad to have finally gotten it working properly.

It is a good thing that libopenzwave doesn't use anything that will cause an issue with it being compiled with a different compiler version then what python has been compiled with. 

There is an issue with compiling/using libopenzwave when running on Stackless python. This has been addressed by the authors/maintainers of stackless python and cython. It had something to do with fastcall and py_eval. It has been repaired and will be functioning with the next release of cython and stackless. I wanted to mention it for historical purposes.

**Pull request merged**
