### PR TITLE
allow index and label for get_values

### PR DESCRIPTION
**Pull request by techgaun**
@bibi21000 I see that many values have labels defined in their configurations. The label was particularly useful for getting `Alarm Level` and `Alarm Type` as I didn't see a way to do by only the previously allowed parameters in get_values. Also, the `index` is useful in cases where for example a device with `COMMAND_CLASS_USER_CODE` command class has user codes and those user codes are indexed from 0 to max number of supported user codes. The `node.get_usercode(index)` gives a simple way for us to get usercode in particular index.

### CODE REVIEW

**Comment by bibi21000** [comment]
Please don't update named parameters unless it's really needed which is not the case here : 

-    def get_values(self, class_id='All', genre='All', \
 -        type='All', readonly='All', writeonly='All'):
 +    def get_values(self, class_id='All', genre='All', type='All', \
 +        readonly='All', writeonly='All', value_index='All', label='All'):
          """
If it's really nedded, please add a line iun changelog

**Comment by techgaun** [comment]
@bibi21000 sorry I didn't understand what you mean. Do you mean I should change `index` parameter to `value_index`?

**Comment by techgaun** [comment]
I used `value_index` initially but I thought it should just match with the attribute so renamed all `value_index` to `index` in next commits.

**Comment by techgaun** [comment]
@bibi21000 now I think about it, I wonder if you are referring to the additions of new arguments (index and label)? It seems that `label` is quite useful because many of the attributes are given labels by OZW so making it easier to query the values. I can update changelog if thats what you are referring to but I think having label is useful and having index as well (for eg. for usercodes where yale lock supports 200+ usercodes and you can make sure you use usercodes from index 0 and so on).

**Comment by bibi21000** [comment]
Hi
I was thinking that you change existing parameters but i make a mistake.
Sorry.
Dont take care of what i said.
I m not at home until the end of the week. Will look at your pr soon.

Le 7 juin 2017 18:22, "Samar Dhwoj Acharya" <notifications@github.com> a
écrit :

**Comment by techgaun** [comment]
@bibi21000 thanks and no problem. Thanks for looking into this.

**Comment by bibi21000** [comment]
thanks

**Pull request merged**
